using Bedrock.Functions.Commands;
using Bedrock.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Bedrock.Functions {
    public class MCFunction : IMCFile {
        public const string AutoGeneratedMessage = "# generated by bedrock.NET";

        public string Name { get; set; }
        public IList<Command> Commands { get; } = new List<Command>();

        public string Path {
            get {
                return "functions/" + Name + ".mcfunction";
            }
        }

        public MCFunction(string name, params Command[] commands) {
            Name = name;
            Commands.AddRange(commands);
        }

        public override string ToString() {
            IList<string> commands = Commands.Select(c => c.ToString()).ToList();
            commands.Insert(0, AutoGeneratedMessage);
            return string.Join("\n", commands);
        }
    }
}
